name: 'dbt_project'
version: '1.0'
config-version: 2

profile: 'dbt_project'

# Définition unique des chemins de modèles
model-paths: ["models"]       

# Optionnel : si tu veux séparer staging et marts, ce sont des sous-dossiers de "models"
# models/
# ├─ staging/ 
# └─ marts/

# Répertoires pour les artefacts de compilation
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
